INSERT INTO public."CodeCIIU"(id,code,sector_id,economic_activity,valid_economic_activity) VALUES 
(gen_random_uuid(), '0111', NULL, 'Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas', TRUE),
(gen_random_uuid(), '0112', NULL, 'Cultivo de arroz', TRUE),
(gen_random_uuid(), '0113', NULL, 'Cultivo de hortalizas, raíces y tubérculos', TRUE),
(gen_random_uuid(), '0114', NULL, 'Cultivo de tabaco', TRUE),
(gen_random_uuid(), '0115', NULL, 'Cultivo de plantas textiles', TRUE),
(gen_random_uuid(), '0119', NULL, 'Otros cultivos transitorios n.c.p.', TRUE),
(gen_random_uuid(), '0121', NULL, 'Cultivo de frutas tropicales y subtropicales', TRUE),
(gen_random_uuid(), '0122', NULL, 'Cultivo de plátano y banano', TRUE),
(gen_random_uuid(), '0123', NULL, 'Cultivo de café', TRUE),
(gen_random_uuid(), '0124', NULL, 'Cultivo de caña de azúcar', TRUE),
(gen_random_uuid(), '0125', NULL, 'Cultivo de flor de corte', TRUE),
(gen_random_uuid(), '0126', NULL, 'Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos', TRUE),
(gen_random_uuid(), '0127', NULL, 'Cultivo de plantas con las que se preparan bebidas', TRUE),
(gen_random_uuid(), '0128', NULL, 'Cultivo de especias y de plantas aromáticas y medicinales', TRUE),
(gen_random_uuid(), '0129', NULL, 'Otros cultivos permanentes n.c.p.', TRUE),
(gen_random_uuid(), '0130', NULL, 'Propagación de plantas (actividades de los viveros, excepto viveros forestales)', TRUE),
(gen_random_uuid(), '0141', NULL, 'Cría de ganado bovino y bufalino', TRUE),
(gen_random_uuid(), '0142', NULL, 'Cría de caballos y otros equinos', TRUE),
(gen_random_uuid(), '0143', NULL, 'Cría de ovejas y cabras', TRUE),
(gen_random_uuid(), '0144', NULL, 'Cría de ganado porcino', TRUE),
(gen_random_uuid(), '0145', NULL, 'Cría de aves de corral', TRUE),
(gen_random_uuid(), '0149', NULL, 'Cría de otros animales n.c.p.', TRUE),
(gen_random_uuid(), '0150', NULL, 'Explotación mixta (agrícola y pecuaria)', TRUE),
(gen_random_uuid(), '0161', NULL, 'Actividades de apoyo a la agricultura', TRUE),
(gen_random_uuid(), '0162', NULL, 'Actividades de apoyo a la ganadería', TRUE),
(gen_random_uuid(), '0163', NULL, 'Actividades posteriores a la cosecha', TRUE),
(gen_random_uuid(), '0164', NULL, 'Tratamiento de semillas para propagación', TRUE),
(gen_random_uuid(), '0170', NULL, 'Caza ordinaria y mediante trampas y actividades de servicios conexas', TRUE),
(gen_random_uuid(), '0210', NULL, 'Silvicultura y otras actividades forestales', FALSE),
(gen_random_uuid(), '0220', NULL, 'Extracción de madera', FALSE),
(gen_random_uuid(), '0230', NULL, 'Recolección de productos forestales diferentes a la madera', FALSE),
(gen_random_uuid(), '0240', NULL, 'Servicios de apoyo a la silvicultura', FALSE),
(gen_random_uuid(), '0311', NULL, 'Pesca marítima', TRUE),
(gen_random_uuid(), '0312', NULL, 'Pesca de agua dulce', TRUE),
(gen_random_uuid(), '0321', NULL, 'Acuicultura marítima', TRUE),
(gen_random_uuid(), '0322', NULL, 'Acuicultura de agua dulce', TRUE),
(gen_random_uuid(), '0510', NULL, 'Extracción de hulla (carbón de piedra)', FALSE),
(gen_random_uuid(), '0520', NULL, 'Extracción de carbón lignito', FALSE),
(gen_random_uuid(), '0610', NULL, 'Extracción de petróleo crudo', FALSE),
(gen_random_uuid(), '0620', NULL, 'Extracción de gas natural', FALSE),
(gen_random_uuid(), '0710', NULL, 'Extracción de minerales de hierro', FALSE),
(gen_random_uuid(), '0721', NULL, 'Extracción de minerales de uranio y de torio', FALSE),
(gen_random_uuid(), '0722', NULL, 'Extracción de oro y otros metales preciosos', FALSE),
(gen_random_uuid(), '0723', NULL, 'Extracción de minerales de níquel', FALSE),
(gen_random_uuid(), '0729', NULL, 'Extracción de otros minerales metalíferos no ferrosos n.c.p.', FALSE),
(gen_random_uuid(), '0811', NULL, 'Extracción de piedra, arena, arcillas comunes, yeso y anhidrita', FALSE),
(gen_random_uuid(), '0812', NULL, 'Extracción de arcillas de uso industrial, caliza, caolín y bentonitas', FALSE),
(gen_random_uuid(), '0820', NULL, 'Extracción de esmeraldas, piedras preciosas y semipreciosas', FALSE),
(gen_random_uuid(), '0891', NULL, 'Extracción de minerales para la fabricación de abonos y productos químicos', FALSE),
(gen_random_uuid(), '0892', NULL, 'Extracción de halita (sal)', FALSE),
(gen_random_uuid(), '0899', NULL, 'Extracción de otros minerales no metálicos n.c.p.', FALSE),
(gen_random_uuid(), '0910', NULL, 'Actividades de apoyo para la extracción de petróleo y de gas natural', FALSE),
(gen_random_uuid(), '0990', NULL, 'Actividades de apoyo para otras actividades de explotación de minas y canteras', FALSE),
(gen_random_uuid(), '1011', NULL, 'Procesamiento y conservación de carne y productos cárnicos', TRUE),
(gen_random_uuid(), '1012', NULL, 'Procesamiento y conservación de pescados, crustáceos y moluscos', TRUE),
(gen_random_uuid(), '1020', NULL, 'Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos', TRUE),
(gen_random_uuid(), '1031', NULL, 'Extracción de aceites de origen vegetal crudos', TRUE),
(gen_random_uuid(), '1032', NULL, 'Elaboración de aceites y grasas de origen vegetal refinados', TRUE),
(gen_random_uuid(), '1033', NULL, 'Elaboración de aceites y grasas de origen animal', TRUE),
(gen_random_uuid(), '1040', NULL, 'Elaboración de productos lácteos', TRUE),
(gen_random_uuid(), '1051', NULL, 'Elaboración de productos de molinería', TRUE),
(gen_random_uuid(), '1052', NULL, 'Elaboración de almidones y productos derivados del almidón', TRUE),
(gen_random_uuid(), '1061', NULL, 'Trilla de café', TRUE),
(gen_random_uuid(), '1062', NULL, 'Descafeinado, tostión y molienda del café', TRUE),
(gen_random_uuid(), '1063', NULL, 'Otros derivados del café', TRUE),
(gen_random_uuid(), '1071', NULL, 'Elaboración y refinación de azúcar', TRUE),
(gen_random_uuid(), '1072', NULL, 'Elaboración de panela', TRUE),
(gen_random_uuid(), '1081', NULL, 'Elaboración de productos de panadería', TRUE),
(gen_random_uuid(), '1082', NULL, 'Elaboración de cacao, chocolate y productos de confitería', TRUE),
(gen_random_uuid(), '1083', NULL, 'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares', TRUE),
(gen_random_uuid(), '1084', NULL, 'Elaboración de comidas y platos preparados', TRUE),
(gen_random_uuid(), '1089', NULL, 'Elaboración de otros productos alimenticios n.c.p.', TRUE),
(gen_random_uuid(), '1090', NULL, 'Elaboración de alimentos preparados para animales', TRUE),
(gen_random_uuid(), '1101', NULL, 'Destilación, rectificación y mezcla de bebidas alcohólicas', TRUE),
(gen_random_uuid(), '1102', NULL, 'Elaboración de bebidas fermentadas no destiladas', TRUE),
(gen_random_uuid(), '1103', NULL, 'Producción de malta, elaboración de cervezas y otras bebidas malteadas', TRUE),
(gen_random_uuid(), '1104', NULL, 'Elaboración de bebidas no alcohólicas, producción de aguas minerales y otras aguas embotelladas', TRUE),
(gen_random_uuid(), '1200', NULL, 'Elaboración de productos de tabaco', FALSE),
(gen_random_uuid(), '1311', NULL, 'Preparación e hilatura de fibras textiles', FALSE),
(gen_random_uuid(), '1312', NULL, 'Tejeduría de productos textiles', FALSE),
(gen_random_uuid(), '1313', NULL, 'Acabado de productos textiles', FALSE),
(gen_random_uuid(), '1391', NULL, 'Fabricación de tejidos de punto y ganchillo', FALSE),
(gen_random_uuid(), '1392', NULL, 'Confección de artículos con materiales textiles, excepto prendas de vestir', FALSE),
(gen_random_uuid(), '1393', NULL, 'Fabricación de tapetes y alfombras para pisos', FALSE),
(gen_random_uuid(), '1394', NULL, 'Fabricación de cuerdas, cordeles, cables, bramantes y redes', FALSE),
(gen_random_uuid(), '1399', NULL, 'Fabricación de otros artículos textiles n.c.p.', FALSE),
(gen_random_uuid(), '1410', NULL, 'Confección de prendas de vestir, excepto prendas de piel', FALSE),
(gen_random_uuid(), '1420', NULL, 'Fabricación de artículos de piel', FALSE),
(gen_random_uuid(), '1430', NULL, 'Fabricación de artículos de punto y ganchillo', FALSE),
(gen_random_uuid(), '1511', NULL, 'Curtido y recurtido de cueros; recurtido y teñido de pieles', FALSE),
(gen_random_uuid(), '1512', NULL, 'Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería', FALSE),
(gen_random_uuid(), '1513', NULL, 'Fabricación de artículos de viaje, bolsos de mano y artículos similares; artículos de talabartería y guarnicionería elaborados en otros materiales', FALSE),
(gen_random_uuid(), '1521', NULL, 'Fabricación de calzado de cuero y piel, con cualquier tipo de suela', FALSE),
(gen_random_uuid(), '1522', NULL, 'Fabricación de otros tipos de calzado, excepto calzado de cuero y piel', FALSE),
(gen_random_uuid(), '1523', NULL, 'Fabricación de partes del calzado', FALSE),
(gen_random_uuid(), '1610', NULL, 'Aserrado, acepillado e impregnación de la madera', FALSE),
(gen_random_uuid(), '1620', NULL, 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles', FALSE),
(gen_random_uuid(), '1630', NULL, 'Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción', FALSE),
(gen_random_uuid(), '1640', NULL, 'Fabricación de recipientes de madera', FALSE),
(gen_random_uuid(), '1690', NULL, 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería', FALSE),
(gen_random_uuid(), '1701', NULL, 'Fabricación de pulpas (pastas) celulósicas; papel y cartón', FALSE),
(gen_random_uuid(), '1702', NULL, 'Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón', FALSE),
(gen_random_uuid(), '1709', NULL, 'Fabricación de otros artículos de papel y cartón', FALSE),
(gen_random_uuid(), '1811', NULL, 'Actividades de impresión', FALSE),
(gen_random_uuid(), '1812', NULL, 'Actividades de servicios relacionados con la impresión', FALSE),
(gen_random_uuid(), '1820', NULL, 'Producción de copias a partir de grabaciones originales', FALSE),
(gen_random_uuid(), '1910', NULL, 'Fabricación de productos de hornos de coque', FALSE),
(gen_random_uuid(), '1921', NULL, 'Fabricación de productos de la refinación del petróleo', FALSE),
(gen_random_uuid(), '1922', NULL, 'Actividad de mezcla de combustibles', FALSE),
(gen_random_uuid(), '2011', NULL, 'Fabricación de sustancias y productos químicos básicos', FALSE),
(gen_random_uuid(), '2012', NULL, 'Fabricación de abonos y compuestos inorgánicos nitrogenados', FALSE),
(gen_random_uuid(), '2013', NULL, 'Fabricación de plásticos en formas primarias', FALSE),
(gen_random_uuid(), '2014', NULL, 'Fabricación de caucho sintético en formas primarias', FALSE),
(gen_random_uuid(), '2021', NULL, 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario', TRUE),
(gen_random_uuid(), '2022', NULL, 'Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas', FALSE),
(gen_random_uuid(), '2023', NULL, 'Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador', FALSE),
(gen_random_uuid(), '2029', NULL, 'Fabricación de otros productos químicos n.c.p.', FALSE),
(gen_random_uuid(), '2030', NULL, 'Fabricación de fibras sintéticas y artificiales', FALSE),
(gen_random_uuid(), '2100', NULL, 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico', FALSE),
(gen_random_uuid(), '2211', NULL, 'Fabricación de llantas y neumáticos de caucho', FALSE),
(gen_random_uuid(), '2212', NULL, 'Reencauche de llantas usadas', FALSE),
(gen_random_uuid(), '2219', NULL, 'Fabricación de formas básicas de caucho y otros productos de caucho n.c.p.', FALSE),
(gen_random_uuid(), '2221', NULL, 'Fabricación de formas básicas de plástico', FALSE),
(gen_random_uuid(), '2229', NULL, 'Fabricación de artículos de plástico n.c.p.', FALSE),
(gen_random_uuid(), '2310', NULL, 'Fabricación de vidrio y productos de vidrio', FALSE),
(gen_random_uuid(), '2391', NULL, 'Fabricación de productos refractarios', FALSE),
(gen_random_uuid(), '2392', NULL, 'Fabricación de materiales de arcilla para la construcción', FALSE),
(gen_random_uuid(), '2393', NULL, 'Fabricación de otros productos de cerámica y porcelana', FALSE),
(gen_random_uuid(), '2394', NULL, 'Fabricación de cemento, cal y yeso', FALSE),
(gen_random_uuid(), '2395', NULL, 'Fabricación de artículos de hormigón, cemento y yeso', FALSE),
(gen_random_uuid(), '2396', NULL, 'Corte, tallado y acabado de la piedra', FALSE),
(gen_random_uuid(), '2399', NULL, 'Fabricación de otros productos minerales no metálicos n.c.p.', FALSE),
(gen_random_uuid(), '2410', NULL, 'Industrias básicas de hierro y de acero', FALSE),
(gen_random_uuid(), '2421', NULL, 'Industrias básicas de metales preciosos', FALSE),
(gen_random_uuid(), '2429', NULL, 'Industrias básicas de otros metales no ferrosos', FALSE),
(gen_random_uuid(), '2431', NULL, 'Fundición de hierro y de acero', FALSE),
(gen_random_uuid(), '2432', NULL, 'Fundición de metales no ferrosos', FALSE),
(gen_random_uuid(), '2511', NULL, 'Fabricación de productos metálicos para uso estructural', FALSE),
(gen_random_uuid(), '2512', NULL, 'Fabricación de tanques, depósitos y recipientes de metal, excepto los utilizados para el envase o el transporte de mercancías', FALSE),
(gen_random_uuid(), '2513', NULL, 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central', FALSE),
(gen_random_uuid(), '2520', NULL, 'Fabricación de armas y municiones', FALSE),
(gen_random_uuid(), '2591', NULL, 'Forja, prensado, estampado y laminado de metal; pulvimetalurgia', FALSE),
(gen_random_uuid(), '2592', NULL, 'Tratamiento y revestimiento de metales; mecanizado', FALSE),
(gen_random_uuid(), '2593', NULL, 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería', FALSE),
(gen_random_uuid(), '2599', NULL, 'Fabricación de otros productos elaborados de metal n.c.p.', FALSE),
(gen_random_uuid(), '2610', NULL, 'Fabricación de componentes y tableros electrónicos', FALSE),
(gen_random_uuid(), '2620', NULL, 'Fabricación de computadoras y de equipo periférico', FALSE),
(gen_random_uuid(), '2630', NULL, 'Fabricación de equipos de comunicación', FALSE),
(gen_random_uuid(), '2640', NULL, 'Fabricación de aparatos electrónicos de consumo', FALSE),
(gen_random_uuid(), '2651', NULL, 'Fabricación de equipo de medición, prueba, navegación y control', FALSE),
(gen_random_uuid(), '2652', NULL, 'Fabricación de relojes', FALSE),
(gen_random_uuid(), '2660', NULL, 'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico', FALSE),
(gen_random_uuid(), '2670', NULL, 'Fabricación de instrumentos ópticos y equipo fotográfico', FALSE),
(gen_random_uuid(), '2680', NULL, 'Fabricación de medios magnéticos y ópticos para almacenamiento de datos', FALSE),
(gen_random_uuid(), '2711', NULL, 'Fabricación de motores, generadores y transformadores eléctricos', FALSE),
(gen_random_uuid(), '2712', NULL, 'Fabricación de aparatos de distribución y control de la energía eléctrica', FALSE),
(gen_random_uuid(), '2720', NULL, 'Fabricación de pilas, baterías y acumuladores eléctricos', FALSE),
(gen_random_uuid(), '2731', NULL, 'Fabricación de hilos y cables eléctricos y de fibra óptica', FALSE),
(gen_random_uuid(), '2732', NULL, 'Fabricación de dispositivos de cableado', FALSE),
(gen_random_uuid(), '2740', NULL, 'Fabricación de equipos eléctricos de iluminación', FALSE),
(gen_random_uuid(), '2750', NULL, 'Fabricación de aparatos de uso doméstico', FALSE),
(gen_random_uuid(), '2790', NULL, 'Fabricación de otros tipos de equipo eléctrico n.c.p.', FALSE),
(gen_random_uuid(), '2811', NULL, 'Fabricación de motores, turbinas, y partes para motores de combustión interna', FALSE),
(gen_random_uuid(), '2812', NULL, 'Fabricación de equipos de potencia hidráulica y neumática', FALSE),
(gen_random_uuid(), '2813', NULL, 'Fabricación de otras bombas, compresores, grifos y válvulas', FALSE),
(gen_random_uuid(), '2814', NULL, 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión', FALSE),
(gen_random_uuid(), '2815', NULL, 'Fabricación de hornos, hogares y quemadores industriales', FALSE),
(gen_random_uuid(), '2816', NULL, 'Fabricación de equipo de elevación y manipulación', FALSE),
(gen_random_uuid(), '2817', NULL, 'Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)', FALSE),
(gen_random_uuid(), '2818', NULL, 'Fabricación de herramientas manuales con motor', FALSE),
(gen_random_uuid(), '2819', NULL, 'Fabricación de otros tipos de maquinaria y equipo de uso general n.c.p.', FALSE),
(gen_random_uuid(), '2821', NULL, 'Fabricación de maquinaria agropecuaria y forestal', TRUE),
(gen_random_uuid(), '2822', NULL, 'Fabricación de máquinas formadoras de metal y de máquinas herramienta', FALSE),
(gen_random_uuid(), '2823', NULL, 'Fabricación de maquinaria para la metalurgia', FALSE),
(gen_random_uuid(), '2824', NULL, 'Fabricación de maquinaria para explotación de minas y canteras y para obras de construcción', FALSE),
(gen_random_uuid(), '2825', NULL, 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco', TRUE),
(gen_random_uuid(), '2826', NULL, 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros', FALSE),
(gen_random_uuid(), '2829', NULL, 'Fabricación de otros tipos de maquinaria y equipo de uso especial n.c.p.', FALSE),
(gen_random_uuid(), '2910', NULL, 'Fabricación de vehículos automotores y sus motores', FALSE),
(gen_random_uuid(), '2920', NULL, 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques', FALSE),
(gen_random_uuid(), '2930', NULL, 'Fabricación de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', FALSE),
(gen_random_uuid(), '3011', NULL, 'Construcción de barcos y de estructuras flotantes', FALSE),
(gen_random_uuid(), '3012', NULL, 'Construcción de embarcaciones de recreo y deporte', FALSE),
(gen_random_uuid(), '3020', NULL, 'Fabricación de locomotoras y de material rodante para ferrocarriles', FALSE),
(gen_random_uuid(), '3030', NULL, 'Fabricación de aeronaves, naves espaciales y de maquinaria conexa', FALSE),
(gen_random_uuid(), '3040', NULL, 'Fabricación de vehículos militares de combate', FALSE),
(gen_random_uuid(), '3091', NULL, 'Fabricación de motocicletas', FALSE),
(gen_random_uuid(), '3092', NULL, 'Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad', FALSE),
(gen_random_uuid(), '3099', NULL, 'Fabricación de otros tipos de equipo de transporte n.c.p.', FALSE),
(gen_random_uuid(), '3110', NULL, 'Fabricación de muebles', FALSE),
(gen_random_uuid(), '3120', NULL, 'Fabricación de colchones y somieres', FALSE),
(gen_random_uuid(), '3211', NULL, 'Fabricación de joyas y artículos conexos', FALSE),
(gen_random_uuid(), '3212', NULL, 'Fabricación de bisutería y artículos conexos', FALSE),
(gen_random_uuid(), '3220', NULL, 'Fabricación de instrumentos musicales', FALSE),
(gen_random_uuid(), '3230', NULL, 'Fabricación de artículos y equipo para la práctica del deporte', FALSE),
(gen_random_uuid(), '3240', NULL, 'Fabricación de juegos, juguetes y rompecabezas', FALSE),
(gen_random_uuid(), '3250', NULL, 'Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)', FALSE),
(gen_random_uuid(), '3290', NULL, 'Otras industrias manufactureras n.c.p.', FALSE),
(gen_random_uuid(), '3311', NULL, 'Mantenimiento y reparación especializado de productos elaborados en metal', FALSE),
(gen_random_uuid(), '3312', NULL, 'Mantenimiento y reparación especializado de maquinaria y equipo', FALSE),
(gen_random_uuid(), '3313', NULL, 'Mantenimiento y reparación especializado de equipo electrónico y óptico', FALSE),
(gen_random_uuid(), '3314', NULL, 'Mantenimiento y reparación especializado de equipo eléctrico', FALSE),
(gen_random_uuid(), '3315', NULL, 'Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas', FALSE),
(gen_random_uuid(), '3319', NULL, 'Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p.', FALSE),
(gen_random_uuid(), '3320', NULL, 'Instalación especializada de maquinaria y equipo industrial', FALSE),
(gen_random_uuid(), '3511', NULL, 'Generación de energía eléctrica', FALSE),
(gen_random_uuid(), '3512', NULL, 'Transmisión de energía eléctrica', FALSE),
(gen_random_uuid(), '3513', NULL, 'Distribución de energía eléctrica', FALSE),
(gen_random_uuid(), '3514', NULL, 'Comercialización de energía eléctrica', FALSE),
(gen_random_uuid(), '3520', NULL, 'Producción de gas; distribución de combustibles gaseosos por tuberías', FALSE),
(gen_random_uuid(), '3530', NULL, 'Suministro de vapor y aire acondicionado', FALSE),
(gen_random_uuid(), '3600', NULL, 'Captación, tratamiento y distribución de agua', FALSE),
(gen_random_uuid(), '3700', NULL, 'Evacuación y tratamiento de aguas residuales', FALSE),
(gen_random_uuid(), '3811', NULL, 'Recolección de desechos no peligrosos', FALSE),
(gen_random_uuid(), '3812', NULL, 'Recolección de desechos peligrosos', FALSE),
(gen_random_uuid(), '3821', NULL, 'Tratamiento y disposición de desechos no peligrosos', FALSE),
(gen_random_uuid(), '3822', NULL, 'Tratamiento y disposición de desechos peligrosos', FALSE),
(gen_random_uuid(), '3830', NULL, 'Recuperación de materiales', FALSE),
(gen_random_uuid(), '3900', NULL, 'Actividades de saneamiento ambiental y otros servicios de gestión de desechos', FALSE),
(gen_random_uuid(), '4111', NULL, 'Construcción de edificios residenciales', FALSE),
(gen_random_uuid(), '4112', NULL, 'Construcción de edificios no residenciales', FALSE),
(gen_random_uuid(), '4210', NULL, 'Construcción de carreteras y vías de ferrocarril', FALSE),
(gen_random_uuid(), '4220', NULL, 'Construcción de proyectos de servicio público', FALSE),
(gen_random_uuid(), '4290', NULL, 'Construcción de otras obras de ingeniería civil', FALSE),
(gen_random_uuid(), '4311', NULL, 'Demolición', FALSE),
(gen_random_uuid(), '4312', NULL, 'Preparación del terreno', FALSE),
(gen_random_uuid(), '4321', NULL, 'Instalaciones eléctricas', FALSE),
(gen_random_uuid(), '4322', NULL, 'Instalaciones de fontanería, calefacción y aire acondicionado', FALSE),
(gen_random_uuid(), '4329', NULL, 'Otras instalaciones especializadas', FALSE),
(gen_random_uuid(), '4330', NULL, 'Terminación y acabado de edificios y obras de ingeniería civil', FALSE),
(gen_random_uuid(), '4390', NULL, 'Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil', FALSE),
(gen_random_uuid(), '4511', NULL, 'Comercio de vehículos automotores nuevos', FALSE),
(gen_random_uuid(), '4512', NULL, 'Comercio de vehículos automotores usados', FALSE),
(gen_random_uuid(), '4520', NULL, 'Mantenimiento y reparación de vehículos automotores', FALSE),
(gen_random_uuid(), '4530', NULL, 'Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores', FALSE),
(gen_random_uuid(), '4541', NULL, 'Comercio de motocicletas y de sus partes, piezas y accesorios', FALSE),
(gen_random_uuid(), '4542', NULL, 'Mantenimiento y reparación de motocicletas y de sus partes y piezas', FALSE),
(gen_random_uuid(), '4610', NULL, 'Comercio al por mayor a cambio de una retribución o por contrata', FALSE),
(gen_random_uuid(), '4620', NULL, 'Comercio al por mayor de materias primas agropecuarias; animales vivos', TRUE),
(gen_random_uuid(), '4631', NULL, 'Comercio al por mayor de productos alimenticios', TRUE),
(gen_random_uuid(), '4632', NULL, 'Comercio al por mayor de bebidas y tabaco', FALSE),
(gen_random_uuid(), '4641', NULL, 'Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico', FALSE),
(gen_random_uuid(), '4642', NULL, 'Comercio al por mayor de prendas de vestir', FALSE),
(gen_random_uuid(), '4643', NULL, 'Comercio al por mayor de calzado', FALSE),
(gen_random_uuid(), '4644', NULL, 'Comercio al por mayor de aparatos y equipo de uso doméstico', FALSE),
(gen_random_uuid(), '4645', NULL, 'Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador', FALSE),
(gen_random_uuid(), '4649', NULL, 'Comercio al por mayor de otros utensilios domésticos n.c.p.', FALSE),
(gen_random_uuid(), '4651', NULL, 'Comercio al por mayor de computadores, equipo periférico y programas de informática', FALSE),
(gen_random_uuid(), '4652', NULL, 'Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones', FALSE),
(gen_random_uuid(), '4653', NULL, 'Comercio al por mayor de maquinaria y equipo agropecuarios', TRUE),
(gen_random_uuid(), '4659', NULL, 'Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p.', FALSE),
(gen_random_uuid(), '4661', NULL, 'Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos', FALSE),
(gen_random_uuid(), '4662', NULL, 'Comercio al por mayor de metales y productos metalíferos', FALSE),
(gen_random_uuid(), '4663', NULL, 'Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción', FALSE),
(gen_random_uuid(), '4664', NULL, 'Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario', TRUE),
(gen_random_uuid(), '4665', NULL, 'Comercio al por mayor de desperdicios, desechos y chatarra', FALSE),
(gen_random_uuid(), '4669', NULL, 'Comercio al por mayor de otros productos n.c.p.', FALSE),
(gen_random_uuid(), '4690', NULL, 'Comercio al por mayor no especializado', FALSE),
(gen_random_uuid(), '4711', NULL, 'Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas (alcohólicas y no alcohólicas) o tabaco', TRUE),
(gen_random_uuid(), '4719', NULL, 'Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas (alcohólicas y no alcohólicas) y tabaco', TRUE),
(gen_random_uuid(), '4721', NULL, 'Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados', TRUE),
(gen_random_uuid(), '4722', NULL, 'Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados', TRUE),
(gen_random_uuid(), '4723', NULL, 'Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados', TRUE),
(gen_random_uuid(), '4724', NULL, 'Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados', TRUE),
(gen_random_uuid(), '4729', NULL, 'Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados', TRUE),
(gen_random_uuid(), '4731', NULL, 'Comercio al por menor de combustible para automotores', FALSE),
(gen_random_uuid(), '4732', NULL, 'Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores', FALSE),
(gen_random_uuid(), '4741', NULL, 'Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados', FALSE),
(gen_random_uuid(), '4742', NULL, 'Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados', FALSE),
(gen_random_uuid(), '4751', NULL, 'Comercio al por menor de productos textiles en establecimientos especializados', FALSE),
(gen_random_uuid(), '4752', NULL, 'Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados', FALSE),
(gen_random_uuid(), '4753', NULL, 'Comercio al por menor de tapices, alfombras y recubrimientos para paredes y pisos en establecimientos especializados', FALSE),
(gen_random_uuid(), '4754', NULL, 'Comercio al por menor de electrodomésticos y gasodomésticos, muebles y equipos de iluminación en establecimientos especializados', FALSE),
(gen_random_uuid(), '4755', NULL, 'Comercio al por menor de artículos y utensilios de uso doméstico en establecimientos especializados', FALSE),
(gen_random_uuid(), '4759', NULL, 'Comercio al por menor de otros artículos domésticos en establecimientos especializados', FALSE),
(gen_random_uuid(), '4761', NULL, 'Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados', FALSE),
(gen_random_uuid(), '4762', NULL, 'Comercio al por menor de artículos deportivos, en establecimientos especializados', FALSE),
(gen_random_uuid(), '4769', NULL, 'Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados', FALSE),
(gen_random_uuid(), '4771', NULL, 'Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados', FALSE),
(gen_random_uuid(), '4772', NULL, 'Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados', FALSE),
(gen_random_uuid(), '4773', NULL, 'Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados', FALSE),
(gen_random_uuid(), '4774', NULL, 'Comercio al por menor de otros productos nuevos en establecimientos especializados', FALSE),
(gen_random_uuid(), '4775', NULL, 'Comercio al por menor de artículos de segunda mano', FALSE),
(gen_random_uuid(), '4781', NULL, 'Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles', TRUE),
(gen_random_uuid(), '4782', NULL, 'Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles', FALSE),
(gen_random_uuid(), '4789', NULL, 'Comercio al por menor de otros productos en puestos de venta móviles', FALSE),
(gen_random_uuid(), '4791', NULL, 'Comercio al por menor realizado a través de internet', FALSE),
(gen_random_uuid(), '4792', NULL, 'Comercio al por menor realizado a través de casas de venta o por correo', FALSE),
(gen_random_uuid(), '4799', NULL, 'Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados', FALSE),
(gen_random_uuid(), '4911', NULL, 'Transporte férreo de pasajeros', FALSE),
(gen_random_uuid(), '4912', NULL, 'Transporte férreo de carga', FALSE),
(gen_random_uuid(), '4921', NULL, 'Transporte de pasajeros', FALSE),
(gen_random_uuid(), '4922', NULL, 'Transporte mixto', FALSE),
(gen_random_uuid(), '4923', NULL, 'Transporte de carga por carretera', FALSE),
(gen_random_uuid(), '4930', NULL, 'Transporte por tuberías', FALSE),
(gen_random_uuid(), '5011', NULL, 'Transporte de pasajeros marítimo y de cabotaje', FALSE),
(gen_random_uuid(), '5012', NULL, 'Transporte de carga marítimo y de cabotaje', FALSE),
(gen_random_uuid(), '5021', NULL, 'Transporte fluvial de pasajeros', FALSE),
(gen_random_uuid(), '5022', NULL, 'Transporte fluvial de carga', FALSE),
(gen_random_uuid(), '5111', NULL, 'Transporte aéreo nacional de pasajeros', FALSE),
(gen_random_uuid(), '5112', NULL, 'Transporte aéreo internacional de pasajeros', FALSE),
(gen_random_uuid(), '5121', NULL, 'Transporte aéreo nacional de carga', FALSE),
(gen_random_uuid(), '5122', NULL, 'Transporte aéreo internacional de carga', FALSE),
(gen_random_uuid(), '5210', NULL, 'Almacenamiento y depósito', FALSE),
(gen_random_uuid(), '5221', NULL, 'Actividades de estaciones, vías y servicios complementarios para el transporte terrestre', FALSE),
(gen_random_uuid(), '5222', NULL, 'Actividades de puertos y servicios complementarios para el transporte acuático', FALSE),
(gen_random_uuid(), '5223', NULL, 'Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo', FALSE),
(gen_random_uuid(), '5224', NULL, 'Manipulación de carga', FALSE),
(gen_random_uuid(), '5229', NULL, 'Otras actividades complementarias al transporte', FALSE),
(gen_random_uuid(), '5310', NULL, 'Actividades postales nacionales', FALSE),
(gen_random_uuid(), '5320', NULL, 'Actividades de mensajería', FALSE),
(gen_random_uuid(), '5511', NULL, 'Alojamiento en hoteles', FALSE),
(gen_random_uuid(), '5512', NULL, 'Alojamiento en apartahoteles', FALSE),
(gen_random_uuid(), '5513', NULL, 'Alojamiento en centros vacacionales', FALSE),
(gen_random_uuid(), '5514', NULL, 'Alojamiento rural', FALSE),
(gen_random_uuid(), '5519', NULL, 'Otros tipos de alojamiento para visitantes', FALSE),
(gen_random_uuid(), '5520', NULL, 'Actividades de zonas de camping y parques para vehículos recreacionales', FALSE),
(gen_random_uuid(), '5530', NULL, 'Servicio de estancia por horas', FALSE),
(gen_random_uuid(), '5590', NULL, 'Otros tipos de alojamiento n.c.p.', FALSE),
(gen_random_uuid(), '5611', NULL, 'Expendio a la mesa de comidas preparadas', FALSE),
(gen_random_uuid(), '5612', NULL, 'Expendio por autoservicio de comidas preparadas', FALSE),
(gen_random_uuid(), '5613', NULL, 'Expendio de comidas preparadas en cafeterías', FALSE),
(gen_random_uuid(), '5619', NULL, 'Otros tipos de expendio de comidas preparadas n.c.p.', FALSE),
(gen_random_uuid(), '5621', NULL, 'Catering para eventos', FALSE),
(gen_random_uuid(), '5629', NULL, 'Actividades de otros servicios de comidas', FALSE),
(gen_random_uuid(), '5630', NULL, 'Expendio de bebidas alcohólicas para el consumo dentro del establecimiento', FALSE),
(gen_random_uuid(), '5811', NULL, 'Edición de libros', FALSE),
(gen_random_uuid(), '5812', NULL, 'Edición de directorios y listas de correo', FALSE),
(gen_random_uuid(), '5813', NULL, 'Edición de periódicos, revistas y otras publicaciones periódicas', FALSE),
(gen_random_uuid(), '5819', NULL, 'Otros trabajos de edición', FALSE),
(gen_random_uuid(), '5820', NULL, 'Edición de programas de informática (software)', FALSE),
(gen_random_uuid(), '5911', NULL, 'Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', FALSE),
(gen_random_uuid(), '5912', NULL, 'Actividades de postproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', FALSE),
(gen_random_uuid(), '5913', NULL, 'Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión', FALSE),
(gen_random_uuid(), '5914', NULL, 'Actividades de exhibición de películas cinematográficas y videos', FALSE),
(gen_random_uuid(), '5920', NULL, 'Actividades de grabación de sonido y edición de música', FALSE),
(gen_random_uuid(), '6010', NULL, 'Actividades de programación y transmisión en el servicio de radiodifusión sonora', FALSE),
(gen_random_uuid(), '6020', NULL, 'Actividades de programación y transmisión de televisión', FALSE),
(gen_random_uuid(), '6110', NULL, 'Actividades de telecomunicaciones alámbricas', FALSE),
(gen_random_uuid(), '6120', NULL, 'Actividades de telecomunicaciones inalámbricas', FALSE),
(gen_random_uuid(), '6130', NULL, 'Actividades de telecomunicación satelital', FALSE),
(gen_random_uuid(), '6190', NULL, 'Otras actividades de telecomunicaciones', FALSE),
(gen_random_uuid(), '6201', NULL, 'Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)', FALSE),
(gen_random_uuid(), '6202', NULL, 'Actividades de consultoría informática y actividades de administración de instalaciones informáticas', FALSE),
(gen_random_uuid(), '6209', NULL, 'Otras actividades de tecnologías de información y actividades de servicios informáticos', FALSE),
(gen_random_uuid(), '6311', NULL, 'Procesamiento de datos, alojamiento (hosting) y actividades relacionadas', FALSE),
(gen_random_uuid(), '6312', NULL, 'Portales web', FALSE),
(gen_random_uuid(), '6391', NULL, 'Actividades de agencias de noticias', FALSE),
(gen_random_uuid(), '6399', NULL, 'Otras actividades de servicios de información n.c.p.', FALSE),
(gen_random_uuid(), '6411', NULL, 'Banco Central', FALSE),
(gen_random_uuid(), '6412', NULL, 'Bancos comerciales', FALSE),
(gen_random_uuid(), '6421', NULL, 'Actividades de las corporaciones financieras', FALSE),
(gen_random_uuid(), '6422', NULL, 'Actividades de las compañías de financiamiento', FALSE),
(gen_random_uuid(), '6423', NULL, 'Banca de segundo piso', FALSE),
(gen_random_uuid(), '6424', NULL, 'Actividades de las cooperativas financieras', FALSE),
(gen_random_uuid(), '6431', NULL, 'Fideicomisos, fondos y entidades financieras similares', FALSE),
(gen_random_uuid(), '6432', NULL, 'Fondos de cesantías', FALSE),
(gen_random_uuid(), '6491', NULL, 'Leasing financiero (arrendamiento financiero)', FALSE),
(gen_random_uuid(), '6492', NULL, 'Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario', FALSE),
(gen_random_uuid(), '6493', NULL, 'Actividades de compra de cartera o factoring', FALSE),
(gen_random_uuid(), '6494', NULL, 'Otras actividades de distribución de fondos', FALSE),
(gen_random_uuid(), '6495', NULL, 'Instituciones especiales oficiales', FALSE),
(gen_random_uuid(), '6496', NULL, 'Capitalización', FALSE),
(gen_random_uuid(), '6499', NULL, 'Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p.', FALSE),
(gen_random_uuid(), '6511', NULL, 'Seguros generales', FALSE),
(gen_random_uuid(), '6512', NULL, 'Seguros de vida', FALSE),
(gen_random_uuid(), '6513', NULL, 'Reaseguros', FALSE),
(gen_random_uuid(), '6515', NULL, 'Seguros de salud', FALSE),
(gen_random_uuid(), '6521', NULL, 'Servicios de seguros sociales de salud', FALSE),
(gen_random_uuid(), '6522', NULL, 'Servicios de seguros sociales en riesgos laborales', FALSE),
(gen_random_uuid(), '6523', NULL, 'Servicios de seguros sociales en riesgos familia', FALSE),
(gen_random_uuid(), '6531', NULL, 'Régimen de prima media con prestación definida (RPM)', FALSE),
(gen_random_uuid(), '6532', NULL, 'Régimen de ahorro individual con solidaridad (RAIS)', FALSE),
(gen_random_uuid(), '6611', NULL, 'Administración de mercados financieros', FALSE),
(gen_random_uuid(), '6612', NULL, 'Corretaje de valores y de contratos de productos básicos', FALSE),
(gen_random_uuid(), '6613', NULL, 'Otras actividades relacionadas con el mercado de valores', FALSE),
(gen_random_uuid(), '6614', NULL, 'Actividades de las sociedades de intermediación cambiaria y de servicios financieros especiales', FALSE),
(gen_random_uuid(), '6615', NULL, 'Actividades de los profesionales de compra y venta de divisas', FALSE),
(gen_random_uuid(), '6619', NULL, 'Otras actividades auxiliares de las actividades de servicios financieros n.c.p.', FALSE),
(gen_random_uuid(), '6621', NULL, 'Actividades de agentes y corredores de seguros', FALSE),
(gen_random_uuid(), '6629', NULL, 'Evaluación de riesgos y daños, y otras actividades de servicios auxiliares', FALSE),
(gen_random_uuid(), '6630', NULL, 'Actividades de administración de fondos', FALSE),
(gen_random_uuid(), '6810', NULL, 'Actividades inmobiliarias realizadas con bienes propios o arrendados', FALSE),
(gen_random_uuid(), '6820', NULL, 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata', FALSE),
(gen_random_uuid(), '6910', NULL, 'Actividades jurídicas', FALSE),
(gen_random_uuid(), '6920', NULL, 'Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria', FALSE),
(gen_random_uuid(), '7010', NULL, 'Actividades de administración empresarial', FALSE),
(gen_random_uuid(), '7020', NULL, 'Actividades de consultoría de gestión', FALSE),
(gen_random_uuid(), '7111', NULL, 'Actividades de arquitectura', FALSE),
(gen_random_uuid(), '7112', NULL, 'Actividades de ingeniería y otras actividades conexas de consultoría técnica', FALSE),
(gen_random_uuid(), '7120', NULL, 'Ensayos y análisis técnicos', FALSE),
(gen_random_uuid(), '7210', NULL, 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería', FALSE),
(gen_random_uuid(), '7220', NULL, 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades', FALSE),
(gen_random_uuid(), '7310', NULL, 'Publicidad', FALSE),
(gen_random_uuid(), '7320', NULL, 'Estudios de mercado y realización de encuestas de opinión pública', FALSE),
(gen_random_uuid(), '7410', NULL, 'Actividades especializadas de diseño', FALSE),
(gen_random_uuid(), '7420', NULL, 'Actividades de fotografía', FALSE),
(gen_random_uuid(), '7490', NULL, 'Otras actividades profesionales, científicas y técnicas n.c.p.', FALSE),
(gen_random_uuid(), '7500', NULL, 'Actividades veterinarias', FALSE),
(gen_random_uuid(), '7710', NULL, 'Alquiler y arrendamiento de vehículos automotores', FALSE),
(gen_random_uuid(), '7721', NULL, 'Alquiler y arrendamiento de equipo recreativo y deportivo', FALSE),
(gen_random_uuid(), '7722', NULL, 'Alquiler de videos y discos', FALSE),
(gen_random_uuid(), '7729', NULL, 'Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p.', FALSE),
(gen_random_uuid(), '7730', NULL, 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p.', FALSE),
(gen_random_uuid(), '7740', NULL, 'Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor', FALSE),
(gen_random_uuid(), '7810', NULL, 'Actividades de agencias de gestión y colocación de empleo', FALSE),
(gen_random_uuid(), '7820', NULL, 'Actividades de empresas de servicios temporales', FALSE),
(gen_random_uuid(), '7830', NULL, 'Otras actividades de provisión de talento humano', FALSE),
(gen_random_uuid(), '7911', NULL, 'Actividades de las agencias de viaje', FALSE),
(gen_random_uuid(), '7912', NULL, 'Actividades de operadores turísticos', FALSE),
(gen_random_uuid(), '7990', NULL, 'Otros servicios de reserva y actividades relacionadas', FALSE),
(gen_random_uuid(), '8010', NULL, 'Actividades de seguridad privada', FALSE),
(gen_random_uuid(), '8020', NULL, 'Actividades de servicios de sistemas de seguridad', FALSE),
(gen_random_uuid(), '8030', NULL, 'Actividades de detectives e investigadores privados', FALSE),
(gen_random_uuid(), '8110', NULL, 'Actividades combinadas de apoyo a instalaciones', FALSE),
(gen_random_uuid(), '8121', NULL, 'Limpieza general interior de edificios', FALSE),
(gen_random_uuid(), '8129', NULL, 'Otras actividades de limpieza de edificios e instalaciones industriales', FALSE),
(gen_random_uuid(), '8130', NULL, 'Actividades de paisajismo y servicios de mantenimiento conexos', FALSE),
(gen_random_uuid(), '8211', NULL, 'Actividades combinadas de servicios administrativos de oficina', FALSE),
(gen_random_uuid(), '8219', NULL, 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina', FALSE),
(gen_random_uuid(), '8220', NULL, 'Actividades de centros de llamadas (call center)', FALSE),
(gen_random_uuid(), '8230', NULL, 'Organización de convenciones y eventos comerciales', FALSE),
(gen_random_uuid(), '8291', NULL, 'Actividades de agencias de cobranza y oficinas de calificación crediticia', FALSE),
(gen_random_uuid(), '8292', NULL, 'Actividades de envase y empaque', FALSE),
(gen_random_uuid(), '8299', NULL, 'Otras actividades de servicio de apoyo a las empresas n.c.p.', FALSE),
(gen_random_uuid(), '8411', NULL, 'Actividades legislativas de la administración pública', FALSE),
(gen_random_uuid(), '8412', NULL, 'Actividades ejecutivas de la administración pública', FALSE),
(gen_random_uuid(), '8413', NULL, 'Regulación de las actividades de organismos que prestan servicios de salud, educativos, culturales y otros servicios sociales, excepto servicios de seguridad social', FALSE),
(gen_random_uuid(), '8414', NULL, 'Actividades reguladoras y facilitadoras de la actividad económica', FALSE),
(gen_random_uuid(), '8415', NULL, 'Actividades de los órganos de control y otras instituciones', FALSE),
(gen_random_uuid(), '8421', NULL, 'Relaciones exteriores', FALSE),
(gen_random_uuid(), '8422', NULL, 'Actividades de defensa', FALSE),
(gen_random_uuid(), '8423', NULL, 'Orden público y actividades de seguridad', FALSE),
(gen_random_uuid(), '8424', NULL, 'Administración de justicia', FALSE),
(gen_random_uuid(), '8430', NULL, 'Actividades de planes de seguridad social de afiliación obligatoria', FALSE),
(gen_random_uuid(), '8511', NULL, 'Educación de la primera infancia', FALSE),
(gen_random_uuid(), '8512', NULL, 'Educación preescolar', FALSE),
(gen_random_uuid(), '8513', NULL, 'Educación básica primaria', FALSE),
(gen_random_uuid(), '8521', NULL, 'Educación básica secundaria', FALSE),
(gen_random_uuid(), '8522', NULL, 'Educación media académica', FALSE),
(gen_random_uuid(), '8523', NULL, 'Educación media técnica', FALSE),
(gen_random_uuid(), '8530', NULL, 'Establecimientos que combinan diferentes niveles de educación', FALSE),
(gen_random_uuid(), '8541', NULL, 'Educación técnica profesional', FALSE),
(gen_random_uuid(), '8542', NULL, 'Educación tecnológica', FALSE),
(gen_random_uuid(), '8543', NULL, 'Educación de instituciones universitarias o de escuelas tecnológicas', FALSE),
(gen_random_uuid(), '8544', NULL, 'Educación de universidades', FALSE),
(gen_random_uuid(), '8551', NULL, 'Formación para el trabajo', FALSE),
(gen_random_uuid(), '8552', NULL, 'Enseñanza deportiva y recreativa', FALSE),
(gen_random_uuid(), '8553', NULL, 'Enseñanza cultural', FALSE),
(gen_random_uuid(), '8559', NULL, 'Otros tipos de educación n.c.p.', FALSE),
(gen_random_uuid(), '8560', NULL, 'Actividades de apoyo a la educación', FALSE),
(gen_random_uuid(), '8610', NULL, 'Actividades de hospitales y clínicas, con internación', FALSE),
(gen_random_uuid(), '8621', NULL, 'Actividades de la práctica médica, sin internación', FALSE),
(gen_random_uuid(), '8622', NULL, 'Actividades de la práctica odontológica', FALSE),
(gen_random_uuid(), '8691', NULL, 'Actividades de apoyo diagnóstico', FALSE),
(gen_random_uuid(), '8692', NULL, 'Actividades de apoyo terapéutico', FALSE),
(gen_random_uuid(), '8699', NULL, 'Otras actividades de atención de la salud humana', FALSE),
(gen_random_uuid(), '8710', NULL, 'Actividades de atención residencial medicalizada de tipo general', FALSE),
(gen_random_uuid(), '8720', NULL, 'Actividades de atención residencial, para el cuidado de pacientes con retardo mental, enfermedad mental y consumo de sustancias psicoactivas', FALSE),
(gen_random_uuid(), '8730', NULL, 'Actividades de atención en instituciones para el cuidado de personas mayores y/o discapacitadas', FALSE),
(gen_random_uuid(), '8790', NULL, 'Otras actividades de atención en instituciones con alojamiento', FALSE),
(gen_random_uuid(), '8810', NULL, 'Actividades de asistencia social sin alojamiento para personas mayores y discapacitadas', FALSE),
(gen_random_uuid(), '8891', NULL, 'Actividades de guarderías para niños y niñas', FALSE),
(gen_random_uuid(), '8899', NULL, 'Otras actividades de asistencia social sin alojamiento n.c.p.', FALSE),
(gen_random_uuid(), '9001', NULL, 'Creación literaria', FALSE),
(gen_random_uuid(), '9002', NULL, 'Creación musical', FALSE),
(gen_random_uuid(), '9003', NULL, 'Creación teatral', FALSE),
(gen_random_uuid(), '9004', NULL, 'Creación audiovisual', FALSE),
(gen_random_uuid(), '9005', NULL, 'Artes plásticas y visuales', FALSE),
(gen_random_uuid(), '9006', NULL, 'Actividades teatrales', FALSE),
(gen_random_uuid(), '9007', NULL, 'Actividades de espectáculos musicales en vivo', FALSE),
(gen_random_uuid(), '9008', NULL, 'Otras actividades de espectáculos en vivo n.c.p.', FALSE),
(gen_random_uuid(), '9101', NULL, 'Actividades de bibliotecas y archivos', FALSE),
(gen_random_uuid(), '9102', NULL, 'Actividades y funcionamiento de museos, conservación de edificios y sitios históricos', FALSE),
(gen_random_uuid(), '9103', NULL, 'Actividades de jardines botánicos, zoológicos y reservas naturales', FALSE),
(gen_random_uuid(), '9200', NULL, 'Actividades de juegos de azar y apuestas', FALSE),
(gen_random_uuid(), '9311', NULL, 'Gestión de instalaciones deportivas', FALSE),
(gen_random_uuid(), '9312', NULL, 'Actividades de clubes deportivos', FALSE),
(gen_random_uuid(), '9319', NULL, 'Otras actividades deportivas', FALSE),
(gen_random_uuid(), '9321', NULL, 'Actividades de parques de atracciones y parques temáticos', FALSE),
(gen_random_uuid(), '9329', NULL, 'Otras actividades recreativas y de esparcimiento n.c.p.', FALSE),
(gen_random_uuid(), '9411', NULL, 'Actividades de asociaciones empresariales y de empleadores', FALSE),
(gen_random_uuid(), '9412', NULL, 'Actividades de asociaciones profesionales', FALSE),
(gen_random_uuid(), '9420', NULL, 'Actividades de sindicatos de empleados', FALSE),
(gen_random_uuid(), '9491', NULL, 'Actividades de asociaciones religiosas', FALSE),
(gen_random_uuid(), '9492', NULL, 'Actividades de asociaciones políticas', FALSE),
(gen_random_uuid(), '9499', NULL, 'Actividades de otras asociaciones n.c.p.', FALSE),
(gen_random_uuid(), '9511', NULL, 'Mantenimiento y reparación de computadores y de equipo periférico', FALSE),
(gen_random_uuid(), '9512', NULL, 'Mantenimiento y reparación de equipos de comunicación', FALSE),
(gen_random_uuid(), '9521', NULL, 'Mantenimiento y reparación de aparatos electrónicos de consumo', FALSE),
(gen_random_uuid(), '9522', NULL, 'Mantenimiento y reparación de aparatos y equipos domésticos y de jardinería', FALSE),
(gen_random_uuid(), '9523', NULL, 'Reparación de calzado y artículos de cuero', FALSE),
(gen_random_uuid(), '9524', NULL, 'Reparación de muebles y accesorios para el hogar', FALSE),
(gen_random_uuid(), '9529', NULL, 'Mantenimiento y reparación de otros efectos personales y enseres domésticos', FALSE),
(gen_random_uuid(), '9601', NULL, 'Lavado y limpieza, incluso la limpieza en seco, de productos textiles y de piel', FALSE),
(gen_random_uuid(), '9602', NULL, 'Peluquería y otros tratamientos de belleza', FALSE),
(gen_random_uuid(), '9603', NULL, 'Pompas fúnebres y actividades relacionadas', FALSE),
(gen_random_uuid(), '9609', NULL, 'Otras actividades de servicios personales n.c.p.', FALSE),
(gen_random_uuid(), '9700', NULL, 'Actividades de los hogares individuales como empleadores de personal doméstico', FALSE),
(gen_random_uuid(), '9810', NULL, 'Actividades no diferenciadas de los hogares individuales como productores de bienes para uso propio', FALSE),
(gen_random_uuid(), '9820', NULL, 'Actividades no diferenciadas de los hogares individuales como productores de servicios para uso propio', FALSE),
(gen_random_uuid(), '9900', NULL, 'Actividades de organizaciones y entidades extraterritoriales', FALSE);
