export const FORM_SELECT_OPTIONS = {
  //GENERAL
  CITY_LIST: 'CITY_LIST',
  GENDER_LIST: 'GENDER_LIST',

  //EDUCATION
  EDUCATION_TITLE_OPTIONS: 'EDUCATION_TITLE_OPTIONS',

  //LANGUAGES
  LANGUAGE_LIST_OPTIONS: 'LANGUAGE_LIST_OPTIONS',
  LANGUAGE_LEVEL_OPTIONS: 'LANGUAGE_LEVEL_OPTIONS',
  AFFIRMATIVE_LIST_OPTIONS: 'AFFIRMATIVE_LIST_OPTIONS',

  //KNOWLEDGE AND SKILLS
  KNOWLEDGE_AND_SKILLS: 'KNOWLEDGE_AND_SKILLS',
  KNOWLEDGE_LIST: 'KNOWLEDGE_LIST',
  SKILLS_LIST: 'SKILLS_LIST',

  //WORK EXPERIENCE
  WORK_ROLE: 'WORK_ROLE',
  EXPERIENCE_RANGE: 'EXPERIENCE_RANGE',

  //BUSINESS
  BUSINESS_LIST: 'BUSINESS_LIST',
  BUSINESS_LIST_ANALYST: 'BUSINESS_LIST_ANALYST',
  BUSINESS_LIST_BY_ROL: 'BUSINESS_LIST_BY_ROL',

  // JOB VACANCY FORM
  BUSINESS_TYPE: 'BUSINESS_TYPE',
  WORK_SECTOR: 'WORK_SECTOR',

  ATTENTION_POINT: 'ATTENTION_POINT',
  MUNICIPALITY_LIST: 'MUNICIPALITY_LIST',
  HIRING_TYPE: 'HIRING_TYPE',
  WORK_MODE: 'WORK_MODE',
  SALARY_RANGE: 'SALARY_RANGE',

  VACANCY_REQ_LANGUAGE: 'VACANCY_REQ_LANGUAGE',
  DISABILITY_TYPE: 'DISABILITY_TYPE',
  WORK_DAYS: 'WORK_DAYS',
  VEHICLE_TYPE: 'VEHICLE_TYPE',
  LABORAL_GESTOR: 'LABORAL_GESTOR',

  // JOB FORM REVISION
  VACANCY_ORIGIN: 'VACANCY_ORIGIN',
  COUNTRY_LIST: 'COUNTRY_LIST',
  LICENSE_TYPE: 'LICENSE_TYPE',

  // JOB VACANCY FORM -> CIIU CODE
  CIIU_CODE_LIST: 'CIIU_CODE_LIST',

  // COURSES
  COURSES_LIST: 'COURSES_LIST',

  // PROGRAM
  PROGRAM_LIST: 'PROGRAM_LIST',

  // ASSISTANCE MODE
  ASSISTANCE_MODE: 'ASSISTANCE_MODE',

  // BACK_OFFICE APPOINTMENT TYPE
  APPOINTMENT_TYPE: 'APPOINTMENT_TYPE',

  REGIONAL_LIST: 'REGIONAL_LIST',
  COURSE_ACCESS_TYPE_LIST: 'COURSE_ACCESS_TYPE_LIST',

  // USER-PROFILE
  CONSULTANTS_LIST: 'CONSULTANTS_LIST',
  ADMIN_PYME_LIST: 'ADMIN_PYME_LIST',

  // PSYCHOLOGIST-TEST
  PSY_TEST_EXAM_LIST: 'PSY_TEST_EXAM_LIST',
};

export const ABILITY_TYPE = {
  KNOWLEDGE: 'CONOCIMIENTOS',
  SKILLS: 'APTITUDES',
};
