import { IsBoolean, IsEmail, IsNotEmpty, IsNumberString, IsOptional, IsString, MaxLength } from "class-validator"

const MAX_STRING_LENGTH = 200
export class CreateUserSiseDto {
    
	//id            // AUTOGENERATED.
    //created_at    // AUTOGENERATED.
    //updated_at    // AUTOGENERATED.
    
    @IsNumberString()
    @IsNotEmpty()
    identification_number : string;

    @IsOptional()
    @IsString()
    @MaxLength(MAX_STRING_LENGTH)
    name : string;
    
    @IsNotEmpty()
    @IsString()
    identification_type : string;

    @IsOptional()
    @IsString()
    @MaxLength(MAX_STRING_LENGTH)
    given_name : string;

    @IsOptional()
    @IsString()
    @MaxLength(MAX_STRING_LENGTH)
    family_name : string;

    @IsOptional()
    @IsEmail()
    @MaxLength(MAX_STRING_LENGTH)
    email : string;

    @IsOptional()
    @IsString()
    @MaxLength(MAX_STRING_LENGTH)
    edcmfndi : string;

    @IsOptional()
    @IsBoolean()
    email_verified : boolean;
}
