import type { Metadata } from "next";
import "@comfanditd/chronux-ui/dist/style.css";
import "./globals.css";
import { Auth } from "@/utils/guards/Auth";
import { StoreProvider } from "@/presentation/components/templates/provider";
import { SessionProviderWrapper } from "@/presentation";
import { ToastContainer } from "@/presentation/components/atoms/common/notifications/Toast";

export const metadata: Metadata = {
  title: "Sucursal Virtual Empresas - Comfandi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <SessionProviderWrapper>
          <StoreProvider>
            <Auth>
              {children}
              <ToastContainer />
            </Auth>
          </StoreProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
