// Generated by https://quicktype.io

export interface SessionInterface {
  exp: number;
  iat: number;
  auth_time: number;
  jti: string;
  iss: string;
  sub: string;
  typ: string;
  azp: string;
  session_state: string;
  scope: string;
  sid: string;
  email_verified: boolean;
  gender: string;
  identification_number: string;
  name: string;
  expedition_date: string;
  identification_type: string;
  preferred_username: string;
  given_name: string;
  family_name: string;
  born_date: string;
  email: string;
}
