import { IsArray, IsBoolean, IsObject, IsOptional, IsString } from "class-validator";
import { SelectOption } from "../../form-utils/entities/form-util.entity";

export class VacantRegisterForm{
    //GeneralInformation{
    @IsArray()
    workRole:Array<SelectOption>;
    @IsString()    
    name:string;
    @IsString()
    nit:string;
    @IsString()    
    comfandiAffiliated:string;
    @IsString()    
    businessSector:string;
    @IsString()    
    address:string;
    @IsString()    
    location:string;
    @IsString() 
    telephone:string;
    @IsString()    
    businessType:string;
    @IsString()    
    businessSize:string;

    //ApplicantInformation{
    @IsString()    
    applicantName:string;
    @IsString()    
    applicantOccupation:string;
    @IsString()        
    identificationNumber:string;
    @IsString()    
    applicantPhone:string;
    //}
    
    //VacantInformation{
    @IsString()    
    vacantName:string;
    @IsString()        
    vacantOccupation:string;
    @IsString()    
    vacantConfidentialRequirements:string;
    @IsString()    
    vacantNumber:string;
    @IsString()    
    vacantOccupationalDenominationCode:string;
    @IsString()    
    vacantCUOCCode:string;
    @IsString()    
    vacantHiringType:string;
    @IsString()    
    vacantOrigin:string;
    @IsString()    
    vacantCountry: string;
    @IsString()    
    vacantWorkMode:string;
    @IsString()    
    @IsOptional()
    vacantWorkRegion:string;
    @IsString()    
    vacantLegalRequirements:string;
    @IsString()    
    vacantSalaryRangeMin:string;
    @IsString()    
    vacantSalary:string;
    @IsString()    
    vacantAttentionPoint:string;
    @IsString()    
    vacantHabilitesDescription:string;
    @IsString()    
    vacantKnowledgeAndSkillsDescription:string;
    @IsString()    
    //}

    //VacantSpecificRequirements{
    reqStudies:string;
    @IsString()    
    reqStudyTitle:string;
    @IsString()    
    reqCertification:string;
    @IsString()    
    reqMinExperience:string;
    @IsString()    
    reqSecondLanguage:string;
    @IsString()    
    @IsOptional()
    reqLanguage:string;
    @IsString()    
    @IsOptional()
    reqLanguageLevel:string;
    @IsString()    
    reqTravel:string;
    @IsString()    
    reqDisabilityOK:string;
    @IsString()    
    reqSectorExperience:string;
    @IsString()    
    reqPersonalInCharge:string;
    @IsString()    
    @IsOptional()
    reqDisabilityType:string;
    @IsString()    
    reqWorkTime:string;
    @IsArray()    
    reqWorkDays:string;
    @IsString()    
    reqVehicle:string;
    @IsString()    
    @IsOptional()
    reqVehicleType:string;
    @IsString()    
    reqDriveLicense:string;
    @IsString()    
    @IsOptional()
    reqDriveLicenseType:string;
    @IsString()    
    @IsOptional()
    reqLikeWorkShop:string;
    @IsString()    
    reqLaboralGestorAssigned:string;
    @IsString()    
    @IsOptional()
    reqObservations:string;
    @IsBoolean()   
    reqDataPolicyOK:string;
    //}
}
