import type { Metadata } from "next";
import "@comfanditd/chronux-ui/dist/style.css";
import "./globals.css";
import { Auth } from "utils/guards/Auth";
import { SessionProviderWrapper, StoreProvider } from "presentation";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Administración Empresarial - Comfandi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <SessionProviderWrapper>
          {/*<Auth>{children}</Auth>*/}
          <StoreProvider>
            <Auth>{children}</Auth>
          </StoreProvider>          
        </SessionProviderWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
