export * from "./CardText";
export * from "./Description";
export * from "./NeutralBlackText";
export * from "./SecondaryText";
export * from "./MainTitle";
export * from "./NumberCircle";
export * from "./ThridText";
export * from "./Greatment";
export * from "./NeutralNCText";
